### ISSUE TITLE
Won't compile on FreeBSD

### ISSUE THREAD

**Issue by GintsR** [haakonnessjoen/MAC-Telnet#24]
`_BSD_AVAILABLE` macro is disabled, thus limiting the functionality available for FreeBSD builds.
Example errors:

mactelnetd.c:334:15: error: 'struct utmpx' has no member named 'ut_host'
  strncpy(utent.ut_host,
               ^
mactelnetd.c:336:29: error: 'struct utmpx' has no member named 'ut_host'
                 sizeof(utent.ut_host));
                             ^
mactelnetd.c:717:9: error: 'index' undeclared (first use in this function)
     if (index >= 0) {
         ^
mactelnetd.c:1150:5: warning: incompatible implicit declaration of built-in function 'bzero'
     bzero(buff, MT_HEADER_LEN);

My workaround in diff.
[diff.txt](https://github.com/haakonnessjoen/MAC-Telnet/files/639317/diff.txt)

**Comment by benben159** [comment]
i've tested your patch, and it doesn't find the libintl library. i've checked that gettext-{tools,runtime} is installed

**Comment by sporkman** [comment]
If like me, you just need the client, there's a few hackarounds.  First, make sure you have the following pkgs installed:

- autoconf
- automake
- gettext-tools
- gmake

Then to build just the client:

- run `./autogen.sh`
- run `./configure`
- edit src/Makefile and add the line `LDFLAGS = -L/usr/local/lib` somewhere in there
- edit src/Makefile and comment out the line that reads `sbin_PROGRAMS = mactelnetd$(EXEEXT)` (ie: put a "#" in front of it)
- run `gmake` in the main directory
- run `gmake install`

The mactelnetd errors look very familiar, the libintl errors just seem to be a broken configure/autotools issue, but I have no clue how to repair that.

Ta-da!  I was only able to make it work with the "-n" switch enabled...  Regardless, got into what was an otherwise inaccessible routerboard.  There is a simpler mactelnet client here, but it's terminal-emulation totally chokes on current Mikrotiks.

**Comment by pautiina** [comment]
fix on https://github.com/haakonnessjoen/MAC-Telnet/pull/43
